package com.kpyruy.takt.core.ui.components

import androidx.compose.material.icons.Icons
import androidx.compose.material.icons.outlined.*
import androidx.compose.ui.graphics.vector.ImageVector

data class CourseIconOption(val key: String, val label: String, val category: String, val vector: ImageVector)

/** Material Design outlined icons, bundled locally; keys remain stable in stored data. */
object CourseIcons {
    val all: List<CourseIconOption> by lazy { listOf(
        CourseIconOption("School", "Освіта школа", "Навчання", Icons.Outlined.School),
        CourseIconOption("MenuBook", "Книга підручник", "Навчання", Icons.Outlined.MenuBook),
        CourseIconOption("AutoStories", "Читання література", "Навчання", Icons.Outlined.AutoStories),
        CourseIconOption("LibraryBooks", "Бібліотека", "Навчання", Icons.Outlined.LibraryBooks),
        CourseIconOption("HistoryEdu", "Історія освіти", "Навчання", Icons.Outlined.HistoryEdu),
        CourseIconOption("EditNote", "Конспект нотатки", "Навчання", Icons.Outlined.EditNote),
        CourseIconOption("Quiz", "Тести питання", "Навчання", Icons.Outlined.Quiz),
        CourseIconOption("Assignment", "Завдання", "Навчання", Icons.Outlined.Assignment),
        CourseIconOption("FactCheck", "Перевірка", "Навчання", Icons.Outlined.FactCheck),
        CourseIconOption("WorkspacePremium", "Диплом нагорода", "Навчання", Icons.Outlined.WorkspacePremium),
        CourseIconOption("Science", "Хімія колба", "Наука", Icons.Outlined.Science),
        CourseIconOption("Biotech", "Біологія мікроскоп", "Наука", Icons.Outlined.Biotech),
        CourseIconOption("Functions", "Математика функція", "Наука", Icons.Outlined.Functions),
        CourseIconOption("Calculate", "Калькулятор", "Наука", Icons.Outlined.Calculate),
        CourseIconOption("SquareFoot", "Геометрія", "Наука", Icons.Outlined.SquareFoot),
        CourseIconOption("Architecture", "Креслення архітектура", "Наука", Icons.Outlined.Architecture),
        CourseIconOption("Straighten", "Лінійка вимірювання", "Наука", Icons.Outlined.Straighten),
        CourseIconOption("Speed", "Фізика швидкість", "Наука", Icons.Outlined.Speed),
        CourseIconOption("ElectricBolt", "Електрика енергія", "Наука", Icons.Outlined.ElectricBolt),
        CourseIconOption("Waves", "Хвилі", "Наука", Icons.Outlined.Waves),
        CourseIconOption("Thermostat", "Температура", "Наука", Icons.Outlined.Thermostat),
        CourseIconOption("WaterDrop", "Рідина вода", "Наука", Icons.Outlined.WaterDrop),
        CourseIconOption("Psychology", "Психологія мозок", "Наука", Icons.Outlined.Psychology),
        CourseIconOption("Public", "Географія світ", "Наука", Icons.Outlined.Public),
        CourseIconOption("Eco", "Екологія листок", "Наука", Icons.Outlined.Eco),
        CourseIconOption("Park", "Дерево природа", "Наука", Icons.Outlined.Park),
        CourseIconOption("Pets", "Тварини", "Наука", Icons.Outlined.Pets),
        CourseIconOption("MedicalServices", "Медицина", "Наука", Icons.Outlined.MedicalServices),
        CourseIconOption("HealthAndSafety", "Здоровʼя", "Наука", Icons.Outlined.HealthAndSafety),
        CourseIconOption("Coronavirus", "Мікробіологія", "Наука", Icons.Outlined.Coronavirus),
        CourseIconOption("Code", "Програмування код", "Технології", Icons.Outlined.Code),
        CourseIconOption("Terminal", "Термінал", "Технології", Icons.Outlined.Terminal),
        CourseIconOption("Computer", "Компʼютер", "Технології", Icons.Outlined.Computer),
        CourseIconOption("Memory", "Процесор електроніка", "Технології", Icons.Outlined.Memory),
        CourseIconOption("DeveloperBoard", "Мікроконтролер", "Технології", Icons.Outlined.DeveloperBoard),
        CourseIconOption("SmartToy", "Робот автоматика", "Технології", Icons.Outlined.SmartToy),
        CourseIconOption("PrecisionManufacturing", "Робототехніка", "Технології", Icons.Outlined.PrecisionManufacturing),
        CourseIconOption("SettingsInputComponent", "Компоненти схеми", "Технології", Icons.Outlined.SettingsInputComponent),
        CourseIconOption("Cable", "Кабель зʼєднання", "Технології", Icons.Outlined.Cable),
        CourseIconOption("Router", "Мережі роутер", "Технології", Icons.Outlined.Router),
        CourseIconOption("Wifi", "Бездротові мережі", "Технології", Icons.Outlined.Wifi),
        CourseIconOption("Storage", "Бази даних", "Технології", Icons.Outlined.Storage),
        CourseIconOption("Cloud", "Хмарні технології", "Технології", Icons.Outlined.Cloud),
        CourseIconOption("Security", "Безпека", "Технології", Icons.Outlined.Security),
        CourseIconOption("BugReport", "Налагодження", "Технології", Icons.Outlined.BugReport),
        CourseIconOption("DataObject", "Дані", "Технології", Icons.Outlined.DataObject),
        CourseIconOption("IntegrationInstructions", "Розробка", "Технології", Icons.Outlined.IntegrationInstructions),
        CourseIconOption("Smartphone", "Мобільні системи", "Технології", Icons.Outlined.Smartphone),
        CourseIconOption("Sensors", "Датчики сенсори", "Технології", Icons.Outlined.Sensors),
        CourseIconOption("Usb", "USB", "Технології", Icons.Outlined.Usb),
        CourseIconOption("Engineering", "Інженерія", "Інженерія", Icons.Outlined.Engineering),
        CourseIconOption("Build", "Інструменти", "Інженерія", Icons.Outlined.Build),
        CourseIconOption("Settings", "Механіка шестерня", "Інженерія", Icons.Outlined.Settings),
        CourseIconOption("Construction", "Будівництво", "Інженерія", Icons.Outlined.Construction),
        CourseIconOption("Handyman", "Майстерня", "Інженерія", Icons.Outlined.Handyman),
        CourseIconOption("Factory", "Виробництво завод", "Інженерія", Icons.Outlined.Factory),
        CourseIconOption("ElectricMeter", "Електричні вимірювання", "Інженерія", Icons.Outlined.ElectricMeter),
        CourseIconOption("SolarPower", "Сонячна енергія", "Інженерія", Icons.Outlined.SolarPower),
        CourseIconOption("WindPower", "Вітрова енергія", "Інженерія", Icons.Outlined.WindPower),
        CourseIconOption("Plumbing", "Труби сантехніка", "Інженерія", Icons.Outlined.Plumbing),
        CourseIconOption("RocketLaunch", "Космос ракета", "Інженерія", Icons.Outlined.RocketLaunch),
        CourseIconOption("Flight", "Авіація літак", "Інженерія", Icons.Outlined.Flight),
        CourseIconOption("DirectionsCar", "Автомобіль транспорт", "Інженерія", Icons.Outlined.DirectionsCar),
        CourseIconOption("Train", "Залізниця", "Інженерія", Icons.Outlined.Train),
        CourseIconOption("BarChart", "Статистика діаграма", "Економіка", Icons.Outlined.BarChart),
        CourseIconOption("PieChart", "Частки діаграма", "Економіка", Icons.Outlined.PieChart),
        CourseIconOption("QueryStats", "Аналітика", "Економіка", Icons.Outlined.QueryStats),
        CourseIconOption("TrendingUp", "Зростання тренд", "Економіка", Icons.Outlined.TrendingUp),
        CourseIconOption("AccountBalance", "Економіка банк", "Економіка", Icons.Outlined.AccountBalance),
        CourseIconOption("Payments", "Фінанси гроші", "Економіка", Icons.Outlined.Payments),
        CourseIconOption("Business", "Бізнес", "Економіка", Icons.Outlined.Business),
        CourseIconOption("Storefront", "Торгівля", "Економіка", Icons.Outlined.Storefront),
        CourseIconOption("Work", "Менеджмент робота", "Економіка", Icons.Outlined.Work),
        CourseIconOption("Balance", "Право баланс", "Економіка", Icons.Outlined.Balance),
        CourseIconOption("Gavel", "Закон", "Економіка", Icons.Outlined.Gavel),
        CourseIconOption("Groups", "Команда", "Економіка", Icons.Outlined.Groups),
        CourseIconOption("Campaign", "Маркетинг", "Економіка", Icons.Outlined.Campaign),
        CourseIconOption("TravelExplore", "Дослідження світу", "Економіка", Icons.Outlined.TravelExplore),
        CourseIconOption("Translate", "Іноземна мова переклад", "Мови й творчість", Icons.Outlined.Translate),
        CourseIconOption("Language", "Мови світ", "Мови й творчість", Icons.Outlined.Language),
        CourseIconOption("Forum", "Дискусія спілкування", "Мови й творчість", Icons.Outlined.Forum),
        CourseIconOption("RecordVoiceOver", "Виступ семінар", "Мови й творчість", Icons.Outlined.RecordVoiceOver),
        CourseIconOption("Mic", "Мікрофон", "Мови й творчість", Icons.Outlined.Mic),
        CourseIconOption("Headphones", "Аудіювання", "Мови й творчість", Icons.Outlined.Headphones),
        CourseIconOption("MusicNote", "Музика", "Мови й творчість", Icons.Outlined.MusicNote),
        CourseIconOption("Piano", "Піаніно", "Мови й творчість", Icons.Outlined.Piano),
        CourseIconOption("Palette", "Мистецтво палітра", "Мови й творчість", Icons.Outlined.Palette),
        CourseIconOption("Brush", "Малювання пензель", "Мови й творчість", Icons.Outlined.Brush),
        CourseIconOption("DesignServices", "Дизайн", "Мови й творчість", Icons.Outlined.DesignServices),
        CourseIconOption("CameraAlt", "Фотографія", "Мови й творчість", Icons.Outlined.CameraAlt),
        CourseIconOption("Movie", "Кіно відео", "Мови й творчість", Icons.Outlined.Movie),
        CourseIconOption("TheaterComedy", "Театр", "Мови й творчість", Icons.Outlined.TheaterComedy),
        CourseIconOption("Draw", "Малюнок", "Мови й творчість", Icons.Outlined.Draw),
        CourseIconOption("Lightbulb", "Ідея лампочка", "Мови й творчість", Icons.Outlined.Lightbulb),
        CourseIconOption("FitnessCenter", "Спорт тренування", "Спорт та інше", Icons.Outlined.FitnessCenter),
        CourseIconOption("SportsSoccer", "Футбол", "Спорт та інше", Icons.Outlined.SportsSoccer),
        CourseIconOption("SportsBasketball", "Баскетбол", "Спорт та інше", Icons.Outlined.SportsBasketball),
        CourseIconOption("Pool", "Плавання", "Спорт та інше", Icons.Outlined.Pool),
        CourseIconOption("DirectionsRun", "Біг", "Спорт та інше", Icons.Outlined.DirectionsRun),
        CourseIconOption("DirectionsBike", "Велосипед", "Спорт та інше", Icons.Outlined.DirectionsBike),
        CourseIconOption("SelfImprovement", "Йога", "Спорт та інше", Icons.Outlined.SelfImprovement),
        CourseIconOption("Hiking", "Туризм", "Спорт та інше", Icons.Outlined.Hiking),
        CourseIconOption("Restaurant", "Харчування", "Спорт та інше", Icons.Outlined.Restaurant),
        CourseIconOption("Coffee", "Кава", "Спорт та інше", Icons.Outlined.Coffee),
        CourseIconOption("Extension", "Пазл", "Спорт та інше", Icons.Outlined.Extension),
        CourseIconOption("Flag", "Мета прапорець", "Спорт та інше", Icons.Outlined.Flag),
        CourseIconOption("StarOutline", "Зірка", "Спорт та інше", Icons.Outlined.StarOutline),
        CourseIconOption("FavoriteBorder", "Серце", "Спорт та інше", Icons.Outlined.FavoriteBorder),
        CourseIconOption("Diamond", "Діамант", "Спорт та інше", Icons.Outlined.Diamond),
    ) }
    fun find(key: String?): CourseIconOption? = all.firstOrNull { it.key == key }
}
