const paths = {
  home:'M3 10 12 3l9 7v10a1 1 0 0 1-1 1h-5v-7H9v7H4a1 1 0 0 1-1-1Z',
  calendar:'M4 5h16v16H4z M7 3v4 M17 3v4 M4 10h16 M8 14h2 M14 14h2 M8 18h2',
  book:'M3 4h6c2 0 3 1 3 2v15c0-2-2-3-4-3H3z M21 4h-6c-2 0-3 1-3 2v15c0-2 2-3 4-3h5z',
  chart:'M4 20V11h4v9 M10 20V7h4v13 M16 20V3h4v17',
  plus:'M12 5v14 M5 12h14', arrow:'M5 12h14 M14 7l5 5-5 5', chevron:'m9 5 7 7-7 7',
  back:'m14 5-7 7 7 7',close:'m6 6 12 12 M18 6 6 18',check:'m5 12 4 4L19 6',
  clock:'M21 12a9 9 0 1 1-18 0 9 9 0 0 1 18 0 M12 7v5l3 2',
  coffee:'M4 8h12v7a5 5 0 0 1-5 5H9a5 5 0 0 1-5-5z M16 8h2a3 3 0 0 1 0 6h-2 M7 3v2 M12 3v2 M3 22h15',
  sun:'M16 12a4 4 0 1 1-8 0 4 4 0 0 1 8 0 M12 2v2 M12 20v2 M2 12h2 M20 12h2 M5 5l1 1 M18 18l1 1 M5 19l1-1 M18 6l1-1',
  moon:'M20 15A9 9 0 0 1 9 4a9 9 0 1 0 11 11Z',
  info:'M21 12a9 9 0 1 1-18 0 9 9 0 0 1 18 0 M12 11v6 M12 7v.2',
  file:'M5 3h9l5 5v13H5z M14 3v6h5 M9 13h6 M9 17h6',
  flag:'M5 21V3 M5 3c5-4 9 4 14 0v10c-5 4-9-4-14 0',
  wifi:'M3 9a15 15 0 0 1 18 0 M6 12a10 10 0 0 1 12 0 M9 15a5 5 0 0 1 6 0 M12 19v.1',
  battery:'M3 7h16v10H3z M21 10v4 M6 10h10v4H6z',
  signal:'M5 19v-4 M10 19v-8 M15 19V7 M20 19V3',
  atom:'M14 12a2 2 0 1 1-4 0 2 2 0 0 1 4 0 M12 2c7 0 7 20 0 20S5 2 12 2 M3 7c4-6 21 4 18 10S0 13 3 7 M3 17c-3-6 14-16 18-10S7 23 3 17',
};
const icon = name => `<svg viewBox="0 0 24 24" aria-hidden="true"><path d="${paths[name] || paths.file}"/></svg>`;
const esc = value => String(value).replace(/[&<>"']/g,c=>({'&':'&amp;','<':'&lt;','>':'&gt;','"':'&quot;',"'":'&#39;'}[c]));
const configs = [
  {id:'pulse',letter:'A',name:'Pulse',tag:'Ясність і ритм',colors:['#355bce','#e9efff','#fff','#ae715d'],note:'Рекомендую як основу',body:'Виразна картка наступної пари, легкий таймлайн і завдання поруч. Найближче до твоїх попередніх виборів, але з сильнішою ієрархією.',tradeoff:'Компроміс: головний акцент активніший, ніж у Studio.'},
  {id:'studio',letter:'B',name:'Studio',tag:'Спокійний планер',colors:['#2e6452','#e5ede3','#f8f7f1','#caa97c'],note:'Більше повітря. Менше тиску.',body:'День як акуратна сторінка планера: тиждень зверху, кольорові поля предметів, м’які поверхні й стримана книжкова типографіка.',tradeoff:'Відхилення для вибору: менше окремих карток, serif-заголовки.'},
  {id:'orbit',letter:'C',name:'Orbit',tag:'Точність і фокус',colors:['#161d1b','#303e29','#d3ec94','#c7b3ec'],note:'Компактний центр навчання',body:'Графіт, лайм і чіткі числові акценти. Час до пари, дедлайни та наступні кроки легко зчитуються навіть у насичений день.',tradeoff:'Компроміс: щільніший, більш інструментальний характер.'},
];
const seeds = () => [{id:'lab',title:'Здати лабораторну №2',course:'FYZI',due:'Сьогодні',complete:false,required:true},{id:'tpar',title:'Розібрати дерева пошуку',course:'TPAR',due:'Завтра',complete:false,required:false}];
const state = Object.fromEntries(configs.map(c=>[c.id,{screen:'home',tab:'overview',calendar:'day',day:22,monthDay:22,tasks:seeds(),mode:'signature',note:'Повторити закони збереження. Звернути увагу на одиниці вимірювання.'}]));
const hosts = {};
function shell(c){return `<article class="concept" data-concept="${c.id}"><div class="concept-heading"><span class="concept-number">${c.letter}</span><h2>${c.name}</h2><span class="descriptor">${c.tag}</span></div><div class="phone" data-style="${c.id}" data-mode="signature" aria-label="${c.name}: інтерактивний макет"><div class="statusbar"><span>09:35</span><span class="status-icons">${icon('signal')}${icon('wifi')}${icon('battery')}</span></div><div class="app-scroll"></div><nav class="bottom-nav" aria-label="${c.name}: навігація"></nav><div class="overlay-root"></div><div class="toast-root" aria-live="polite"></div></div><div class="concept-notes"><div class="swatches">${c.colors.map(color=>`<i style="background:${color}"></i>`).join('')}<span>${c.id==='orbit'?'Graphite / lime':c.id==='studio'?'Sage / paper':'Cobalt / cloud'}</span></div><b>${c.note}</b><p>${c.body}</p><p style="margin-top:9px;font-size:11px">${c.tradeoff}</p></div></article>`}
document.querySelector('#concepts').innerHTML=configs.map(shell).join('');
configs.forEach(c=>hosts[c.id]=document.querySelector(`[data-style="${c.id}"]`));
const sec=(title,action='',target='')=>`<div class="section-title"><h3>${title}</h3>${action?`<button data-go="${target}">${action}${icon('chevron')}</button>`:''}</div>`;
function header(id,title,sub='Вівторок, 22 вересня',back=false){return `<header class="app-header"><div>${sub?`<p class="overline">${sub}</p>`:''}<h2>${title}</h2></div><button class="icon-button" data-action="${back?'home':'theme'}" aria-label="${back?'На головну':'Змінити тему'}">${icon(back?'back':isDark(id)?'sun':'moon')}</button></header>`}
function isDark(id){return state[id].mode==='dark'||(id==='orbit'&&state[id].mode==='signature')}
function tasks(id,all=false){let items=state[id].tasks;if(['course','exam'].includes(state[id].screen))items=items.filter(t=>t.course==='FYZI');return `<div class="task-list">${items.map(t=>`<div class="task-row ${t.complete?'done':''}"><button class="task-check" data-task="${t.id}" aria-label="${esc(t.title)}: ${t.complete?'відновити':'виконати'}" aria-pressed="${t.complete}"><span>${t.complete?icon('check'):''}</span></button><div class="task-text"><strong>${esc(t.title)}</strong><small>${esc(t.course)}${t.required?' · Для допуску':''}</small></div><span class="due" ${t.due!=='Сьогодні'?'style="color:var(--muted)"':''}>${t.complete?'Готово':esc(t.due)}</span></div>`).join('')}</div>${all?`<div class="quiet-note">${icon('check')}4 обов’язкові роботи вже виконано</div>`:''}`}
function homeTimeline(){return `<div class="timeline"><div class="timeline-row past"><div class="times"><strong>08:00</strong>09:30</div><div class="rail"><i class="dot" style="--subject:var(--purple)"></i></div><button class="lesson" data-action="lesson" data-title="Matematika III" data-time="08:00–09:30" data-room="B-204"><strong>Matematika III</strong><small>Лекція · B-204 · Завершено</small></button></div><div class="timeline-row current"><div class="times"><strong>10:00</strong>11:30</div><div class="rail"><i class="dot"></i></div><button class="lesson" data-go="course"><strong>Fyzika</strong><small>Лекція · AB-32 · Наступна</small></button></div><div class="gap">${icon('coffee')}45 хв для себе</div><div class="timeline-row"><div class="times"><strong>12:15</strong>13:45</div><div class="rail"><i class="dot" style="--subject:var(--green)"></i></div><button class="lesson" data-action="lesson" data-title="Teória programovania" data-time="12:15–13:45" data-room="B-112"><strong>Teória programovania</strong><small>Практика · B-112</small></button></div></div>`}
function credits(){return `<div class="credit-mini"><span><b>81</b> / 180 кредитів</span><div class="mini-progress" aria-label="45% програми виконано">${'<i></i>'.repeat(11)}</div></div>`}
function quick(){return `<div class="quick-actions"><button data-action="add">${icon('plus')}Додати</button><button data-go="plan">${icon('chart')}Мій прогрес</button></div>`}
function home(id){const remaining=state[id].tasks.filter(t=>!t.complete).length;
 if(id==='studio')return `${header(id,'Твій вівторок.','Takt · Вересень 2026')}${week(id)}<div class="studio-lead"><span class="date-square">22</span><div><b>Усе йде своїм ритмом.</b><p>Ще 2 пари · ${remaining} ${remaining===1?'завдання':'завдання'} попереду</p></div></div><div class="studio-agenda"><div class="studio-event" style="--subject:var(--purple)"><div class="times"><strong>08:00</strong>09:30</div><div class="event-body"><button data-action="lesson" data-title="Matematika III" data-time="08:00–09:30" data-room="B-204"><strong>Matematika III</strong><p>B-204 · Завершено</p></button></div></div><div class="studio-event next" style="--subject:var(--accent)"><div class="times"><strong>10:00</strong>11:30</div><div class="event-body"><button data-go="course"><span class="eyeline">${icon('clock')}ЧЕРЕЗ 25 ХВИЛИН</span><strong>Fyzika</strong><p>Лекція · AB-32</p></button></div></div><div class="studio-break">45 хв вільного часу</div><div class="studio-event" style="--subject:var(--amber)"><div class="times"><strong>12:15</strong>13:45</div><div class="event-body"><button data-action="lesson" data-title="Teória programovania" data-time="12:15–13:45" data-room="B-112"><strong>Teória programovania</strong><p>Практика · B-112</p></button></div></div></div>${sec('Не загубити важливе','Усі','tasks')}${tasks(id)}<div class="quiet-note">${icon('check')}Одна пара вже позаду. Рухаємося далі.</div>${credits()}${quick()}`;
 if(id==='orbit')return `${header(id,'Тримай ритм.','Takt / Вівторок, 22 вересня')}<div class="orbit-hero"><div class="orbit-hero-top"><div class="next-label"><span>НАСТУПНА ПАРА</span>${icon('clock')}</div><h3>Fyzika</h3><p>Лекція · AB-32</p></div><div class="countdown"><div><strong>25<small>хв</small></strong></div><span class="time-range">10:00—11:30</span></div><button class="orbit-hero-foot" data-go="course">Відкрити предмет${icon('arrow')}</button></div><div class="orbit-stats"><div class="orbit-stat"><strong>02</strong><span>пари<br>попереду</span></div><div class="orbit-stat"><strong>${String(remaining).padStart(2,'0')}</strong><span>активні<br>завдання</span></div></div>${sec('Найближчі дедлайни','Усі','tasks')}${tasks(id)}${sec('Далі за розкладом','День','calendar')}<div class="orbit-events"><div class="orbit-event selected"><span>10:00</span><div class="code" style="--subject:var(--accent)"><b>Fyzika</b><small>Лекція · 90 хв</small></div><span>AB-32</span></div><div class="orbit-event"><span>12:15</span><div class="code" style="--subject:var(--purple)"><b>Teória programovania</b><small>Практика · 90 хв</small></div><span>B-112</span></div></div>${credits()}${quick()}`;
 return `${header(id,'Сьогодні')}<button class="next-card" data-go="course"><div class="next-label"><span>Наступна пара</span>${icon('arrow')}</div><h3>Fyzika</h3><p>Лекція · AB-32</p><div class="next-bottom"><span class="time">10:00–11:30</span><span>Через 25 хв</span></div></button><div class="summary-inline"><span><b>2</b> пари попереду</span><span><b>${remaining}</b> активні завдання</span></div>${sec('Не пропусти','Усі','tasks')}${tasks(id)}${sec('Твій розклад','Календар','calendar')}${homeTimeline()}${credits()}${quick()}`;
}
function week(id){return `<div class="week-strip" aria-label="Тиждень 21–27 вересня">${['Пн','Вт','Ср','Чт','Пт','Сб','Нд'].map((d,i)=>`<button class="day ${state[id].day===i+21?'active':''}" data-day="${i+21}" aria-label="${i+21} вересня" aria-pressed="${state[id].day===i+21}"><span>${d}</span><strong>${i+21}</strong><i class="tiny-dot" style="opacity:${i<5?1:0}"></i></button>`).join('')}</div>`}
function calDay(id){if(state[id].day!==22)return `<div class="panel"><div class="panel-title">${state[id].day} вересня</div><h3 style="font-size:20px;margin-bottom:12px">Вільний день</h3><p>Для цієї дати у демо немає подій. Додай свою через + або повернись до 22 вересня.</p></div>`;return `<div class="calendar-deadline">${icon('flag')}${state[id].tasks.find(t=>t.id==='lab').complete?'Виконано · Лабораторна №2':'Без часу · Здати лабораторну №2'}</div><div class="calendar-grid">${Array.from({length:8},(_,i)=>`<div class="hour"><span>${String(i+8).padStart(2,'0')}:00</span></div>`).join('')}<button class="cal-event" data-past style="top:0;height:96px;--subject:var(--purple);--event-bg:var(--purple-soft)" data-action="lesson" data-title="Matematika III" data-time="08:00–09:30" data-room="B-204"><strong>Matematika III</strong><small>08:00–09:30 · B-204</small></button><div class="now-line"><span>09:35</span></div><button class="cal-event" style="top:128px;height:96px;--subject:var(--accent);--event-bg:var(--soft)" data-go="course"><strong>Fyzika</strong><small>10:00–11:30 · AB-32</small></button><span class="cal-gap" style="top:239px">45 хв вільно</span><button class="cal-event" style="top:272px;height:96px;--subject:var(--green);--event-bg:var(--green-soft)" data-action="lesson" data-title="Teória programovania" data-time="12:15–13:45" data-room="B-112"><strong>Teória programovania</strong><small>12:15–13:45 · B-112</small></button></div>`}
function calWeek(){return [['Пн','21','09:00 · Algoritmy a dátové štruktúry','B-118 · Практика'],['Вт','22','08:00 · Matematika III','B-204 · Лекція'],['Ср','23','10:00 · Anglický jazyk','C-206 · Практика'],['Чт','24','08:00 · Fyzika','AB-32 · Практика'],['Пт','25','12:15 · Teória programovania','B-112 · Лекція']].map(([d,n,t,r])=>`<div class="week-list-day"><div>${d}<b>${n}</b></div><div class="week-list-events"><p>${t}<small>${r}</small></p>${n==='22'?'<p>10:00 · Fyzika<small>AB-32 · Лекція</small></p><p>12:15 · Teória programovania<small>B-112 · Практика</small></p>':''}</div></div>`).join('')}
function calendar(id){const s=state[id];return `${header(id,'Календар','Вересень 2026 · 39 тиждень')}<div class="tabs" aria-label="Формат календаря">${[['day','День'],['week','Тиждень'],['month','Місяць']].map(([key,label])=>`<button class="${s.calendar===key?'active':''}" data-calendar="${key}" aria-pressed="${s.calendar===key}">${label}</button>`).join('')}</div>${s.calendar==='day'?`${week(id)}${calDay(id)}`:s.calendar==='week'?calWeek():`<div class="month-grid">${['П','В','С','Ч','П','С','Н'].map(x=>`<span class="weekday">${x}</span>`).join('')}<span></span>${Array.from({length:30},(_,i)=>`<button class="day ${s.monthDay===i+1?'active':''}" data-month-day="${i+1}" aria-pressed="${s.monthDay===i+1}">${i+1}${[21,22,23,24,25].includes(i+1)?'<i class="tiny-dot"></i>':''}</button>`).join('')}</div>${sec(`${s.monthDay} вересня`)}${s.monthDay===22?homeTimeline():'<div class="panel"><p>У демо на цю дату немає подій.</p></div>'}`}`}
function admission(id){const done=state[id].tasks.find(t=>t.id==='lab').complete;return `<div class="admission ${done?'complete':''}"><div class="admission-head">${icon(done?'check':'info')}${done?'Допуск отримано':'До допуску — одна робота'}</div><div class="steps" aria-label="${done?5:4} із 5 вимог виконано">${Array.from({length:5},(_,i)=>`<i class="${i<(done?5:4)?'filled':''}"></i>`).join('')}</div><p>${done?'5 із 5 обов’язкових робіт виконано. Умови допуску закриті.':'4 із 5 виконано. Залишилося здати лабораторну №2. Бали за неї не нараховуються.'}</p></div>`}
function gradeTargets(){return `<div class="panel"><div class="panel-title">Потрібно набрати на іспиті</div>${[['A','68'],['B','59'],['C','50'],['D','41'],['E','32']].map(([g,p])=>`<div class="target-row"><span><b class="grade">${g}</b><small>Від ${{A:92,B:83,C:74,D:65,E:56}[g]} / 100</small></span><b>${p} / 70</b></div>`).join('')}<p style="margin-top:12px">Розрахунок із 24 уже набраних балів. Остаточної оцінки ще немає.</p></div>`}
function course(id,exam=false){const s=state[id];const active=exam?'exam':s.tab;return `${header(id,'Предмет','3 семестр · 6 кредитів',true)}<div class="course-head"><span class="course-icon">${icon('atom')}</span><div class="course-code"><i class="dot"></i> FYZI_6B</div><h2>Fyzika</h2><p>Іспит · Шкала A–FX</p></div><div class="tabs" aria-label="Вкладки предмета">${[['overview','Огляд'],['tasks','Роботи'],['exam','Іспит'],['notes','Нотатки']].map(([key,label])=>`<button class="${active===key?'active':''}" data-tab="${key}" aria-pressed="${active===key}">${label}</button>`).join('')}</div>${active==='exam'?`<div class="exam-banner"><div class="next-label"><span>Підсумковий іспит</span><span>Спроба 1 / 3</span></div><div class="exam-date">18 січня, 09:00</div><p>2027 · AB-32 · Письмовий іспит</p></div><div class="exam-metrics"><div class="panel"><strong>24<span style="font-size:14px;color:var(--muted)"> / 30</span></strong><small>Набрано за семестр</small></div><div class="panel"><strong>70</strong><small>Балів ще на іспиті</small></div></div><div class="panel"><div class="panel-title">Досяжний максимум <b style="color:var(--accent)">94 / 100 · A</b></div><div class="progress"><i style="width:24%"></i><i class="potential" style="width:70%"></i></div><p>24 набрано + до 70 на іспиті. Це потенціал, а не отримана оцінка.</p></div>${admission(id)}${gradeTargets()}${sec('Матеріали')}<button class="sheet-option" data-action="material"><span>${icon('file')}</span><div><strong>Питання до іспиту</strong><small>Демонстраційна нотатка</small></div></button>`:active==='tasks'?`${admission(id)}${sec('Найближчі роботи')}${tasks(id,true)}${quick()}`:active==='notes'?`<div class="panel"><div class="panel-title">Моя підготовка</div><label for="notes-${id}" class="small-note">Нотатки до предмета</label><textarea class="notes-area" id="notes-${id}">${esc(s.note)}</textarea><p style="margin-top:10px">Зміни зберігаються в цьому демо до перезавантаження.</p></div>`:`<div class="panel"><div class="panel-title">Набрано за семестр<span>Оцінювання триває</span></div><div class="point-value"><b>24</b><span>/ 30 балів</span></div><div class="progress"><i style="width:80%"></i></div><p>До 70 балів ще можна отримати на іспиті.</p></div>${admission(id)}${sec('Найближчі роботи')}${tasks(id)}<button class="primary-button" data-go="exam">Що потрібно для бажаної оцінки?</button>`}`}
function plan(id){return `${header(id,'Твій прогрес','B-PIAR · Демонстраційний план',true)}<div class="panel"><div class="panel-title">Закрито кредитів</div><div class="point-value"><b>81</b><span>/ 180</span></div><div class="progress"><i style="width:45%"></i></div><p>45% шляху вже пройдено. Поріг 180 показано як приклад із поточного UI, це не перевірка виконання блоків навчального плану.</p></div>${sec('Цього семестру')}<button class="sheet-option" data-go="course"><span>${icon('atom')}</span><div><strong>Fyzika</strong><small>6 кредитів · Іспит · 24 / 30 балів</small></div></button><div class="sheet-option"><span>${icon('book')}</span><div><strong>Teória programovania</strong><small>6 кредитів · Навчання триває</small></div></div><div class="sheet-option"><span>${icon('check')}</span><div><strong>Telesná kultúra</strong><small>Залік · Виконано · Без A–FX</small></div></div>${admission(id)}`}
function nav(id){const screen=state[id].screen;return [['home','home','Сьогодні'],['calendar','calendar','Календар'],['add','plus','Додати'],['course','book','Предмети'],['plan','chart','Прогрес']].map(([to,ico,label])=>to==='add'?`<button class="add" data-action="add" aria-label="Додати">${icon(ico)}</button>`:`<button data-go="${to}" ${screen===to||(to==='course'&&['exam','tasks'].includes(screen))?'aria-current="page"':''}>${icon(ico)}<span>${label}</span></button>`).join('')+'<span class="gesture" aria-hidden="true"></span>'}
function render(id,keepScroll=false){const root=hosts[id],s=state[id],scroll=root.querySelector('.app-scroll'),old=scroll.scrollTop;root.dataset.mode=s.mode;scroll.innerHTML=s.screen==='home'?home(id):s.screen==='calendar'?calendar(id):s.screen==='plan'?plan(id):s.screen==='tasks'?`${header(id,'Завдання','Найближчі дедлайни',true)}${tasks(id,true)}${quick()}`:course(id,s.screen==='exam');root.querySelector('.bottom-nav').innerHTML=nav(id);scroll.scrollTop=keepScroll?old:0}
function go(id,to){state[id].screen=to;render(id);}
function sheet(id,content){hosts[id].querySelector('.overlay-root').innerHTML=`<div class="sheet-backdrop"><section class="sheet" role="dialog" aria-modal="true" aria-label="Дії"><div class="sheet-handle"></div>${content}</section></div>`;hosts[id].querySelector('.sheet button,.sheet input')?.focus();}
function sheetHeader(title){return `<div class="section-title"><h3>${title}</h3><button class="icon-button" data-action="close" aria-label="Закрити">${icon('close')}</button></div>`}
function close(id){hosts[id].querySelector('.overlay-root').innerHTML='';hosts[id].querySelector('.add').focus()}
function toast(id,message){const host=hosts[id].querySelector('.toast-root');host.innerHTML=`<div class="toast">${esc(message)}</div>`;clearTimeout(state[id].toastTimer);state[id].toastTimer=setTimeout(()=>host.innerHTML='',2800)}
function add(id){sheet(id,`${sheetHeader('Що додамо?')}<p class="sheet-subtitle">Маленький крок, щоб розвантажити голову.</p>${[['task','check','Завдання','Домашня робота або дедлайн'],['event','calendar','Подія','Додаткова пара або зустріч'],['note','file','Нотатка','Зберегти думку до предмета']].map(([type,ico,title,sub])=>`<button class="sheet-option" data-create="${type}"><span>${icon(ico)}</span><div><strong>${title}</strong><small>${sub}</small></div></button>`).join('')}`)}
function create(id,type){const title=type==='task'?'Нове завдання':type==='event'?'Нова подія':'Нова нотатка';sheet(id,`${sheetHeader(title)}<form data-form="${type}"><label for="title-${id}">Назва</label><input id="title-${id}" name="title" required maxlength="100" placeholder="${type==='task'?'Наприклад, повторити механіку':'Коротка назва'}"><label for="subject-${id}">Предмет</label><select id="subject-${id}" name="subject"><option value="FYZI">Fyzika</option>${type==='note'?'':'<option value="TPAR">Teória programovania</option>'}</select>${type!=='note'?`<label for="date-${id}">Дата</label><input id="date-${id}" type="date" name="date" value="2026-09-22" required>`:''}${type==='event'?`<label for="time-${id}">Час</label><input id="time-${id}" type="time" name="time" value="15:00" required>`:''}<button class="primary-button" type="submit">Додати</button><p class="sheet-subtitle" style="margin-top:12px">Це локальне демо. Дані не потрапляють в Android-застосунок.</p></form>`)}
configs.forEach(({id})=>{
 hosts[id].addEventListener('click',e=>{const b=e.target.closest('button');if(!b)return;
  if(b.dataset.go){go(id,b.dataset.go);return}
  if(b.dataset.task){const task=state[id].tasks.find(t=>t.id===b.dataset.task);task.complete=!task.complete;render(id,true);return}
  if(b.dataset.tab){state[id].tab=b.dataset.tab;state[id].screen='course';render(id);return}
  if(b.dataset.calendar){state[id].calendar=b.dataset.calendar;render(id);return}
  if(b.dataset.day){state[id].day=+b.dataset.day;state[id].screen='calendar';state[id].calendar='day';render(id);return}
  if(b.dataset.monthDay){state[id].monthDay=+b.dataset.monthDay;render(id,true);return}
  if(b.dataset.create){create(id,b.dataset.create);return}
  switch(b.dataset.action){case 'home':go(id,'home');break;case 'theme':state[id].mode=isDark(id)?'light':'dark';render(id,true);break;case 'add':add(id);break;case 'close':close(id);break;case 'material':sheet(id,`${sheetHeader('Питання до іспиту')}<p class="sheet-subtitle">Демонстраційний матеріал</p><div class="panel" style="margin-top:16px"><p>1. Закони Ньютона.<br>2. Імпульс і закон збереження.<br>3. Робота та енергія.<br>4. Гармонічні коливання.</p></div>`);break;case 'lesson':sheet(id,`${sheetHeader(esc(b.dataset.title))}<div class="panel"><div class="panel-title">22 вересня · Розклад</div><h3>${esc(b.dataset.time)}</h3><p style="margin-top:12px">Аудиторія ${esc(b.dataset.room)}</p></div><button class="primary-button" data-action="close">Зрозуміло</button>`);break}
 });
 hosts[id].addEventListener('input',e=>{if(e.target.classList.contains('notes-area'))state[id].note=e.target.value});
 hosts[id].addEventListener('submit',e=>{e.preventDefault();const form=e.target,fields=new FormData(form),title=String(fields.get('title')||'').trim();if(!title)return;const type=form.dataset.form;
 if(type==='note'){state[id].note+=(state[id].note?'\n':'')+title;state[id].tab='notes';state[id].screen='course';}
 else if(type==='task'){const date=String(fields.get('date'));state[id].tasks.push({id:'new-'+Date.now(),title,course:String(fields.get('subject')),due:date==='2026-09-22'?'Сьогодні':date==='2026-09-23'?'Завтра':date.slice(8)+'.'+date.slice(5,7),complete:false,required:false});state[id].screen='tasks';}
 else {state[id].events??=[];state[id].events.push({title,date:String(fields.get('date')),time:String(fields.get('time')),subject:String(fields.get('subject'))});state[id].screen='calendar';state[id].calendar='day';state[id].day=Number(String(fields.get('date')).slice(8));}
 close(id);render(id);toast(id,'Додано до цього макета');
 });
 hosts[id].addEventListener('keydown',e=>{const dialog=hosts[id].querySelector('.sheet');if(!dialog)return;if(e.key==='Escape'){close(id);return}if(e.key==='Tab'){const items=[...dialog.querySelectorAll('button,input,select,textarea')];const first=items[0],last=items[items.length-1];if(e.shiftKey&&document.activeElement===first){e.preventDefault();last.focus()}else if(!e.shiftKey&&document.activeElement===last){e.preventDefault();first.focus()}}});
});
// Added events are deliberately listed separately rather than forcing arbitrary durations onto the time grid.
const originalCalendar=calendar;
calendar=function(id){let html=originalCalendar(id);const events=state[id].events||[];if(events.length)html+=`${sec('Додані події')}${events.map(ev=>`<div class="panel"><div class="panel-title">${esc(ev.date)} · ${esc(ev.time)} · ${esc(ev.subject)}</div><h3 style="font-size:14px">${esc(ev.title)}</h3></div>`).join('')}`;return html;};
document.querySelectorAll('[data-screen]').forEach(button=>button.addEventListener('click',()=>{document.querySelectorAll('[data-screen]').forEach(b=>b.setAttribute('aria-pressed',String(b===button)));configs.forEach(({id})=>{state[id].tab='overview';go(id,button.dataset.screen)})}));
document.querySelector('#appearance').addEventListener('change',e=>configs.forEach(({id})=>{state[id].mode=e.target.value;render(id,true)}));
document.querySelector('#reset').addEventListener('click',()=>{configs.forEach(({id})=>{clearTimeout(state[id].toastTimer);state[id]={screen:'home',tab:'overview',calendar:'day',day:22,monthDay:22,tasks:seeds(),mode:'signature',note:'Повторити закони збереження. Звернути увагу на одиниці вимірювання.'};hosts[id].querySelector('.overlay-root').innerHTML='';hosts[id].querySelector('.toast-root').innerHTML='';render(id)});document.querySelector('#appearance').value='signature';document.querySelectorAll('[data-screen]').forEach(b=>b.setAttribute('aria-pressed',String(b.dataset.screen==='home')))});
const params=new URLSearchParams(location.search);
if(params.has('screen'))configs.forEach(({id})=>{if(['home','calendar','course','exam','plan','tasks'].includes(params.get('screen')))state[id].screen=params.get('screen')});
if(params.has('mode'))configs.forEach(({id})=>state[id].mode=params.get('mode'));
configs.forEach(({id})=>render(id));
